### PR TITLE
Prepare repo for npm publishing

### PR DESCRIPTION
**Pull request by airtonix**
solves #48.

Changes are: 
- un minified code lives in `src`
- process files end up in `build` (examples remain where they are)
- `bower.json` and `package.json` point at processed file.
- `gruntfile` points at relevant places.

Suggestions:
- include `grunt-gh-pages` (or something similar)

### CODE REVIEW

**Comment by baptistebriel** [comment]
+1! When will this PR be merged?

**Comment by Maximilianos** [comment]
+1

**Comment by broskoski** [comment]
+1

**Comment by atran** [comment]
+ 1

**Comment by xpluscal** [comment]
+!

**Comment by OutThisLife** [comment]
+1

**Comment by airtonix** [comment]
It'll be merged when it gets merged. Filling up the comments with unproductive +1s will do nothing...

I don't even remember what this package is...

**Pull request closed without merging**
